owner: trivectortraffic
repo: travelvu-upptime

sites:
  - name: TravelVu Web
    url: https://www.travelvu.app/
  - name: TravelVu Admin
    url: https://rvu.trivector.se/site/login
  - name: TravelViewer UI
    url: https://www.travelviewer.app
  - name: TravelVu API
    url: https://rvu.trivector.se/yii-server/api/get-modes
  - name: TravelViewer API
    url: https://api.travelviewer.app/health
  - name: TravelVu Registry
    url: https://registry.travelvu.io/
    expectedStatusCodes:
      - 401
  - name: TravelVu ACME
    url: https://acme.travelvu.io/health
  - name: TravelVu Public Dev
    url: https://whoami.vs.travelvu.dev/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.travelvu.io
  #baseUrl: /travelvu-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TravelVu Upptime
  introTitle: "**TravelVu** system and services status."
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://support.travelvu.app/
